### ISSUE TITLE
brak tlumaczenia na stronie

### ISSUE THREAD

**Issue by kamilxunai** [mudita/mudita-center#1048]
elo 👋,
w https://mudita.com/submit-an-idea/#moj-pomysl-jest-wyjatkowy-chce-podpisac-nda naglowek jest po polsku mimo ze cala strona jest po angielsku, 
dacie radę fixnąć? ;)

<img width="1308" alt="Screenshot 2022-11-23 at 14 21 48" src="https://user-images.githubusercontent.com/7757534/203594643-fa976f8f-01c4-421d-b295-084b30e04ad9.png">

**Comment by dkarski** [comment]
@kamilxunai 👋 Dzięki za zgłoszenie 🙌  Zaraportowałem błąd. Zajmiemy się tym 🤞
