### ISSUE TITLE
Add or edit notes

### ISSUE THREAD

**Issue by vandys** [mudita/mudita-center#1065]
# 🚀 Feature request

## 📝 Description

It would be very nice to enter note text via my desktop, rather than pecking it in via the number pad.

## 📝 Describe the solution you'd like

I imagine a simple text pane.  You click an existing note or enter a new name, then you get a text input object.  You can paste text, or type it in, then save.

## 📝 Describe alternatives you've considered

Helpful notes can be entered via the phone itself, but this is very tedious once you get paste a sentence or so

**Comment by dkarski** [comment]
Hello!

First, thank you for reporting this feature need.

We are planning to implement this functionality. Unfortunately, I cannot say that will be and when delivered.

**Comment by vandys** [comment]
Another way to solve the notes creation problem would be for the MTP-accessible storage of the phone to let the user place .txt files which become read-only notes on the app.  Then I can mount my phone from my PC and copy content right over.

**Comment by dkarski** [comment]
We've temporarily paused work on the notes feature to focus on other areas important to our users. Closing this ticket for now, but we'll keep you updated on any progress. Feel free to open a new ticket for any questions or suggestions. Apologies for the delayed response; I'll strive to be more responsive in the future.
