### ISSUE TITLE
Manage Pure "ringtones"

### ISSUE THREAD

**Issue by fsbox666** [mudita/mudita-center#1079]
# 🚀 Feature request

## 📝 Description

Mudita has a limited number of ringtones which are not necessarily easily audible (especially when the phone has to be far away from the user's location because of the low SAR antenna network weaknesses)

## 📝 Describe the solution you'd like

(It could obviously be done on the phone itself, but it seems more ergonomical to me to do it in Mudita Center...) Either choose ringtone among the music files of the device or upload short ringtones to the Pure.

## 📝 Describe alternatives you've considered

I do not think there are any... but am happy to hear from you.

**Comment by karolinailnicka** [comment]
Hi! 

Thank you for reporting this feature need.

We do not yet have this feature planned on our roadmap. We'll discuss it with our team and update you then.

**Comment by dkarski** [comment]
Thank you for reporting this feature request. Currently, it is not planned, but we will discuss it with our team and keep you updated on any progress. I'm closing this ticket, but rest assured, we will keep you informed of any developments. If you have any other suggestions or questions, feel free to reach out to us. And remember, feel free to open a new issue if needed.
