### ISSUE TITLE
Phone with Broken Filesystem Cannot be Restored 

### ISSUE THREAD

**Issue by LinuxLounge22** [mudita/mudita-center#1130]
An update left my Mudita Pure’s filesystem in an unusable state, there is currently no function of Mudita Center to fix this issue

**Comment by LinuxLounge22** [comment]
I have reached out to the support team and unfortunately they were unable to help me because I purchased my Mudita Pure used and the original seller had lost their receipt, so there’s nothing I can do with the device until this issue can be fixed in software

**Comment by dkarski** [comment]
Thank you for the update. I've reached out to my team regarding this issue, and while I can't promise an immediate solution, I want to assure you that we're aware of the problem and are working to find a resolution. As soon as I have more information, I'll make sure to update you here. Thank you for your understanding.
