### ISSUE TITLE
Could I submit this app to flathub?

### ISSUE THREAD

**Issue by adamthiede** [mudita/mudita-center#2166]
# 🚀 Feature request

Flathub submission

## 📝 Description

I would like this app to be available on flathub, and I've successfully built it into a flatpak for my personal usage. All it does is unpack the appimage and rebuild it into a flatpak. This is helpful for those who would rather use flatpaks or operating systems where appimages don't work well.

## 📝 Describe the solution you'd like

I would submit the application to flathub.

## 📝 Describe alternatives you've considered

I'd build a flatpak for myself and just use it without submitting it to flathub.

If I'm given a go-ahead I'll submit a manifest I have to flathub, supply a link to this issue as "verification", and then report back here.

The manifest in question is just this: https://github.com/adamthiede/flathub/blob/my-app-submission/com.mudita.mudita-center.yaml

All it's doing is extracting the appimage and packaging it as a flatpak; there is no modification of your code going on here, just a rebuild.

**Comment by adamthiede** [comment]
I've opened a PR to flathub here: https://github.com/flathub/flathub/pull/5903

I'd appreciate if a maintainer here could review or sign-off on it. Or, if you'd rather the application not be on flathub, please also let me know.

**Comment by lkowalczyk87** [comment]
Hello, thank you for contacting us. Unfortunately, we cannot grant permission for publication on our behalf. Please use the prepared package solely for your own purposes. We will consider implementing such a distribution method ourselves.

**Comment by adamthiede** [comment]
Thanks for letting me know. I've closed the PR to flathub and will just use this myself. Please consider submitting the application to flathub in the future.
