### ISSUE TITLE
New macOS icon

### ISSUE THREAD

**Issue by jturner** [mudita/mudita-center#614]
Attached is a new [macOS icon](https://github.com/mudita/mudita-center/files/7955595/icon.icns.zip) for Mudita Center that is square with rounded corners to better match the new icon design of macOS. I used [figma](https://www.figma.com) and this [icon template](https://www.figma.com/community/file/857303226040719059) to create the icon using the favicon svg from the Mudita website.

Feel free to create your own but the current icon just seems out of place to me. Thanks!

[icon.icns.zip](https://github.com/mudita/mudita-center/files/7955595/icon.icns.zip)

**Comment by dkarski** [comment]
@jturner - Thank you 🙇 We are going to take your suggestion. 

You can follow the status as part of this [PR#616](https://github.com/mudita/mudita-center/pull/616) 😉
