### ISSUE TITLE
Wayland support on Linux

### ISSUE THREAD

**Issue by illfygli** [mudita/mudita-center#719]
# 🚀 Feature request
Wayland support would be great. Right now it just crashes under Wayland.
## 📝 Description
The version of Electron used does not seem to support Wayland.
Installing `xwayland` allows it to run as if under X, but then display scaling and other things don't work well instead.

## 📝 Describe the solution you'd like
Update Electron version to 12 or later.
Other Electron apps have the same problem, but with them you can enable Wayland with some flags.

## 📝 Describe alternatives you've considered
As mentioned, `xwayland` makes it run, but poorly.

Cheers ♥

**Comment by dkarski** [comment]
@illfygli, Currently, we are having a little problem with updating the electron to the latest version even to 12. Project dependencies don't allow us to easily update it. However, we going to try again this quarter 🤞

**Comment by dkarski** [comment]
In version 2.2.6, we've updated Electron to version 26.0.0, which should address the Wayland issues you mentioned. Sorry for the delayed response. Please check if it's working better now. If you're still encountering difficulties, let us know! I'm temporarily closing this ticket, but feel free to reopen it if you need further assistance.
