### ISSUE TITLE
ElectronJS unhidden features

### ISSUE THREAD

**Issue by adamgas** [mudita/mudita-center#725]
# 🐛 Bug report
Some windows show ElectronJS toolbar. Globally, Ctrl+Shift+I triggers developer tools

## 📝 Description

Windows show unneccessary toolbar, which enables things like undo, reload and help from ElectronJS.
Developer tools allow to fiddle with looks, data and code.
![image](https://user-images.githubusercontent.com/74133777/169465381-0dfa4869-372c-4e5d-b9d8-32973c92a7f1.png)

## 👍 Expected behavior

Hide toolbar in every window. Common shortcut should not trigger dev tools.

## 👎 Current behavior

The toolbar is showing, developer tools are triggered by common shortcut.

## 🔬 Minimal Reproduction

Connect phone to Mudita Center
Contacts > Import > Login with Google
Window with toolbar shows up

Help - window with toolbar shows up

Anywhere in Mudita Center - Ctrl+Shift+I shows developer tools

Issues that don't have enough info and can't be reproduced will be closed.

## 🌍 Your operating system and Mudita Center version
 W11 Home
1.3.0

## 🤔 Anything else relevant?
Is it a feature?

**Comment by dkarski** [comment]
Hey @adamgas, thanks for opening this issue.

I have reported the issue to our team that will take care of it 😉 

Thank you for your insight and have a good day ❤️

**Comment by dkarski** [comment]
Hey @adamgas,

Thank you for bringing this issue to our attention. I wanted to inform you that this problem should no longer occur in the latest version of Mudita Center. I'm closing this issue now. If you encounter any further issues or have any other concerns, please feel free to create a new ticket, and I'll respond promptly.

Thanks again for your understanding and support!

Best regards,
