### ISSUE TITLE
Import vcf UTF-8 encoding

### ISSUE THREAD

**Issue by adamgas** [mudita/mudita-center#726]
# 🐛 Bug report
When trying to import contacts with polish letters ąęćłń etc. through vcf file got wrong characters

## 📝 Description

When vcf file is encoded in UTF-8, which preserves polish letters, got wrong characters when importing. For example:
vcf file 
```
BEGIN:VCARD
VERSION:3.0
FN:Ąąćć
N:SURNąMę;NąMĘ ąłść;;;
TEL;TYPE=CELL:123 456 789
CATEGORIES:myContacts
END:VCARD
```
got me 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/74133777/169474432-67fbcd65-112d-4c3c-8a07-9d065b97a805.png">

## 👍 Expected behavior

It should import special characters properly.

## 👎 Current behavior

Instead of special characters - it imports some junk.

## 🔬 Minimal Reproduction

Contacts > Import >Import from vcf file
Import .vcf file with UTF-8

## 🌍 Your operating system and Mudita Center version
W11 Home
1.3.0

## 🤔 Anything else relevant?
If it matters - I exported vcf file from Google Contacts page.

**Comment by dkarski** [comment]
Hey @adamgas again! Thank you very much for opening next issue 💪 

I have reported the issue to our team that will take care of it 😉

Thank you very much for your insight  ❤️❤️❤️

**Comment by dkarski** [comment]
This issue should be covered in https://github.com/mudita/mudita-center/pull/774. The fix will be published as part of the 1.5.0 release.

**Comment by dkarski** [comment]
Please check our [latest](https://github.com/mudita/mudita-center/releases/tag/1.5.0) version to confirm that we are handled your case 🙏

**Comment by dkarski** [comment]
The issue should be resolved by now. Since there hasn't been any response, we're closing the ticket. If you encounter any further issues, please let us know.
