### ISSUE TITLE
vcf incompatibilities / cannot import contacts

### ISSUE THREAD

**Issue by agentlibre** [mudita/mudita-center#789]
# 🐛 Bug report

Critical, since Mudita Pure cannot be even reasonably used as a dumb phone without contact importation...

## 📝 Description

I cannot import contacts using the "IMPORT FROM VCF FILE" feature. I have tried with 3 different vcf lists (different vcf versions from 2.4 to 4.0), including with reduced fields. It does not work: message = "no contact to import"

Upon inspection, it appears to me that Mudita Center only accepts vcf version 4.2. I haven't found a way to upgrade my vcf files to this version. The best I could do was using Thunderbird, which converted the contacts to 4.0; still doesn't work.

Someone else already reported this issue on the Community Forum: https://forum.mudita.com/t/unable-to-import-contacts-no-contacts-to-import/4190 

## 👍 Expected behavior

.vcf files should be importable, regardless of their versioning (2.0; 3.0; 4.0). Permitting only 4.2 vcf files is excessive.

## 👎 Current behavior

Contact cannot be imported using vcf features when vcf files are of an earlier version than 4.2.

## 🔬 Minimal Reproduction

Download any vcf file from a source which only provides vcf version earlier than 4.2. Try to import it using the dedicated feature on Mudita Center (appimage).

## 🌍 My operating system / Mudita Center version; MuditaOS version

Ubuntu 20.04 / Mudita Center 1.3.1; MuditaOS 1.2.1

## 🤔 Anything else relevant?

A solution, or at least a very handy workaround, would be to set up a carddav/caldav sync on Mudita Center: https://forum.mudita.com/t/suggestion-ability-to-sync-contacts-calendar-from-your-email-via-caldav-carddav/1875/20

Many thanks for your support !

**Comment by p-sims** [comment]
Same problem here. Can't find a Tool for converting from v3.0 to v4.2

**Comment by dkarski** [comment]
Hi :wave:  I wasn't able to reproduce your issues with the VCARD version in v3.0 / v.4.0. Are you able to send me some example data for your case where I will be able to reproduce the issue? 🙏 

You can send a file here or to my email 👉  daniel.karski@mudita.com

**Comment by dkarski** [comment]
Please ignore my previous comment. I've found reproduce path and I'm working on it. The issue will be handled in the near release 🤞

**Comment by p-sims** [comment]
[iCloud Exported vcards (v3.0) example that mudita centre won't import.vcf.zip](https://github.com/mudita/mudita-center/files/9284565/iCloud.Exported.vcards.v3.0.example.that.mudita.centre.won.t.import.vcf.zip)

@dkarski You may have found the issue now, but here is an example vcf file which doesn't import (says no contacts). It was exported from icloud.com and I think the issue relates to 'item2' entry . . .

**Comment by Phenitei** [comment]
Hi @dkarski, I can unfortunately confirm that this or a similar issue is still occuring, with version 1.5.2. I am using a VCF file with version 2.1, I will try to find out more precisely why the file is refused. It contains ENCODING-PRINTABLE strings and BASE64 pictures, which may be the issue ?

**Comment by dkarski** [comment]
The issue with contact import should no longer persist. However, if users continue to encounter problems, please create a new report detailing the issue. This report is now closed. I apologize for the delay in response and assure you that I will reply promptly.
