### ISSUE TITLE
synchronization failure with Pure

### ISSUE THREAD

**Issue by esope** [mudita/mudita-center#817]
# 🐛 Bug report

## 📝 Description

Mudita center v1.4.1 displays the message ``Unfortunately, synchronization failed Please try to reconnect your device`` after plugging the Pure phone v1.2.1. It happens every time.

## 👍 Expected behavior

Synchronization should succeed.

## 👎 Current behavior

Synchronization fails.

## 🔬 Minimal Reproduction

1. Open Mudita Center
2. Plug the Pure phone
3. Enter the pin code
4. After a few seconds, the synchronization failure message is displayed.

## 🌍 Your operating system and Mudita Center version

Linux. Mudita center 1.4.1. Pure phone 1.2.1.

## 🤔 Anything else relevant?

**This bug should be flagged as "blocking"**, since it makes Mudita Center completely unusable with the Pure phone.
Everything was OK with the 1.4.0 or 1.3.0 if I remember correctly.

**Comment by igorbezsmertnyi** [comment]
Hi @esope!
Thx for reporting the issue. But, we will need additional information from you. Could you please follow the instructions below and send to us the logs from Mudita Center. It makes it easier to debug Your problem.

1. Connect your Pure to a computer where you have installed [Mudita Center](https://mudita.com/products/software-apps/mudita-center/). Open Mudita Center (make sure it’s the most recent version of Mudita Center).
2. Once your phone is connected to Mudita Center, click “Help”. A new window will appear.
3. Click the button marked below:
<img width="1013" alt="Screen Shot 2022-07-01 at 10 29 33 AM" src="https://user-images.githubusercontent.com/21984930/176856917-9b826e4f-d90b-49cb-9673-df4b8cdd9428.png">
4. Fill out the form with your email address. The serial number of your phone is included automatically. You don’t need to put the serial number in the message field.
5. Click SEND. Please don’t unplug your device during sending.

**Comment by esope** [comment]
OK. Done.

**Comment by esope** [comment]
Has it been any progress on this issue?
For the record, it has also been reported by the community here https://forum.mudita.com/t/mudita-center-on-1-4-1-crashing/4568

**Comment by wercix** [comment]
Hi @esope!
We released a new version of Mudita Center 1.4.2 with the fix of the bug you reported.
It should resolve your problem.

**Comment by esope** [comment]
Excellent! Thanks!
I confirm it is now working again as expected.
