### ISSUE TITLE
"Mudita Pure crashed" at every launch of Mudita Center

### ISSUE THREAD

**Issue by esope** [mudita/mudita-center#970]
# 🐛 Bug report

## 📝 Description

Every time I open Mudita Center with the phone already plugged in, a message "Mudita pure crashed" is displayed and invites me to send logs to the maintainers. Nothing weird is visible on the phone (no reboot or unexpected behavior).

## 👍 Expected behavior

Mudita pure should not crash, or at least not every time!

## 👎 Current behavior

Mudita Pure is detected has having crashed every time the Mudita Center connects to the phone.

## 🔬 Minimal Reproduction

1. plug the phone to your computer
2. answer "No" to the question for tethering
3. launch Mudita Center
4. the "Mudita Pure has crashed" dialog is displayed

## 🌍 Your operating system and Mudita Center version

Linux (Linuxmint 21)
Mudita Center 1.5.2
Mudita Pure 1.3.0

## 🤔 Anything else relevant?

Nope

**Comment by wojcik92michal** [comment]
Hello @esope 

I would like to confirm one thing - did you manage to send logs? It would help us with investigating the issue.

**Comment by esope** [comment]
Hi, yes, I have already sent logs many times. I resent one a few minutes ago (search for `#970` in the log message).
The bug continues to occur with the new 1.5.3 release.

**Comment by esope** [comment]
FYI the bug is still there with the 1.4.0 release of MuditaOS.
